flowchart LR

subgraph 0["src"]
subgraph 1["app"]
subgraph 2["core"]
3["accounts"]
4["categorisation"]
5["data-access"]
6["import"]
7["layout"]
8["links"]
9["ml"]
A["onboarding"]
B["state"]
C["stats"]
D["storage"]
E["theme"]
F["transactions"]
G["transfers"]
end
H["feature-accounts"]
I["feature-categories"]
J["feature-changelog"]
K["feature-dashboard"]
L["feature-data-management"]
M["feature-explore"]
N["feature-help"]
O["feature-home"]
P["feature-import"]
Q["feature-income"]
R["feature-learning"]
S["feature-settings"]
T["feature-transactions"]
subgraph U["shared"]
V["echarts"]
W["ui"]
X["utils"]
end
end
end
3-->5
3-->G
3-->X
4-->5
4-->3
5-->9
5-->E
5-->X
6-->5
6-->X
6-->G
7-->B
7-->W
9-->4
9-->5
B-->3
B-->5
B-->C
B-->G
B-->X
B-->F
B-->E
B-->V
C-->5
C-->X
C-->G
C-->3
C-->4
F-->5
F-->G
G-->5
G-->3
G-->X
H-->5
H-->V
H-->B
H-->W
H-->X
H-->C
I-->4
I-->5
I-->B
I-->W
I-->X
I-->9
J-->W
K-->5
K-->B
K-->W
K-->X
K-->G
K-->C
K-->V
L-->5
L-->D
L-->W
L-->X
M-->W
M-->B
M-->C
M-->X
M-->G
M-->V
N-->W
O-->8
O-->W
P-->5
P-->H
P-->W
P-->6
P-->X
P-->B
P-->4
Q-->C
Q-->W
Q-->X
Q-->5
Q-->B
Q-->E
Q-->G
Q-->V
Q-->N
R-->W
R-->I
R-->9
R-->B
R-->5
R-->X
S-->W
S-->8
S-->B
S-->X
S-->L
S-->E
T-->5
T-->B
T-->F
T-->W
T-->X
T-->4
T-->I
T-->G
V-->X
W-->X
