flowchart LR

subgraph 0["src"]
subgraph 1["app"]
subgraph 2["core"]
3["accounts"]
4["categorisation"]
5["data-access"]
6["import"]
7["layout"]
8["links"]
9["ml"]
A["onboarding"]
B["state"]
C["stats"]
D["storage"]
E["theme"]
F["transactions"]
G["transfers"]
end
H["feature-accounts"]
I["feature-categories"]
J["feature-changelog"]
K["feature-dashboard"]
L["feature-data-management"]
M["feature-explore"]
N["feature-help"]
O["feature-home"]
P["feature-import"]
Q["feature-income"]
R["feature-learning"]
S["feature-recurring"]
T["feature-settings"]
U["feature-transactions"]
subgraph V["shared"]
W["echarts"]
X["ui"]
Y["utils"]
end
end
end
3-->5
3-->G
3-->Y
4-->5
4-->3
5-->9
5-->E
5-->Y
6-->5
6-->Y
6-->G
7-->B
7-->X
9-->4
9-->5
B-->3
B-->5
B-->C
B-->G
B-->Y
B-->F
B-->E
B-->W
C-->5
C-->Y
C-->G
C-->3
C-->4
F-->5
F-->G
G-->5
G-->3
G-->Y
H-->5
H-->W
H-->B
H-->X
H-->Y
H-->C
I-->4
I-->5
I-->B
I-->X
I-->Y
I-->9
J-->X
K-->5
K-->B
K-->X
K-->Y
K-->G
K-->C
K-->W
L-->5
L-->D
L-->X
L-->Y
M-->B
M-->X
M-->C
M-->W
M-->Y
N-->X
O-->8
O-->X
P-->5
P-->H
P-->X
P-->6
P-->Y
P-->B
P-->4
Q-->C
Q-->X
Q-->Y
Q-->5
Q-->B
Q-->E
Q-->G
Q-->W
Q-->N
R-->X
R-->I
R-->9
R-->B
R-->5
R-->Y
S-->X
S-->B
S-->C
S-->Y
S-->G
S-->W
T-->X
T-->8
T-->B
T-->Y
T-->L
T-->E
U-->5
U-->B
U-->F
U-->X
U-->Y
U-->4
U-->I
U-->G
W-->Y
X-->Y
X-->B
