flowchart LR

subgraph 0["src"]
subgraph 1["app"]
subgraph 2["core"]
3["accounts"]
4["categorisation"]
5["data-access"]
6["import"]
7["layout"]
8["links"]
9["ml"]
A["onboarding"]
B["state"]
C["stats"]
D["storage"]
E["theme"]
F["transactions"]
G["transfers"]
end
H["feature-accounts"]
I["feature-categories"]
J["feature-changelog"]
K["feature-dashboard"]
L["feature-data-management"]
M["feature-explore"]
N["feature-future"]
O["feature-help"]
P["feature-home"]
Q["feature-import"]
R["feature-income"]
S["feature-learning"]
T["feature-loans"]
U["feature-recurring"]
V["feature-settings"]
W["feature-transactions"]
subgraph X["shared"]
Y["echarts"]
Z["ui"]
10["utils"]
end
end
end
3-->5
3-->G
3-->10
4-->5
4-->3
5-->9
5-->C
5-->E
5-->10
6-->5
6-->10
6-->G
7-->B
7-->Z
9-->4
9-->5
B-->3
B-->5
B-->C
B-->G
B-->10
B-->F
B-->E
B-->Y
C-->5
C-->10
C-->G
C-->3
C-->4
F-->5
F-->G
G-->5
G-->3
G-->10
H-->5
H-->Y
H-->B
H-->Z
H-->10
H-->C
I-->4
I-->5
I-->B
I-->Z
I-->10
I-->9
J-->Z
K-->5
K-->B
K-->Z
K-->10
K-->G
K-->C
K-->Y
L-->5
L-->D
L-->Z
L-->10
M-->B
M-->Z
M-->C
M-->Y
M-->10
M-->5
M-->G
N-->5
N-->B
N-->C
N-->Z
N-->10
N-->G
N-->Y
O-->Z
P-->8
P-->Z
Q-->5
Q-->H
Q-->Z
Q-->6
Q-->10
Q-->B
Q-->4
R-->C
R-->Z
R-->10
R-->5
R-->B
R-->E
R-->G
R-->Y
R-->O
S-->Z
S-->I
S-->9
S-->B
S-->5
S-->10
T-->5
T-->B
T-->Z
T-->10
U-->Z
U-->B
U-->C
U-->10
U-->G
U-->Y
V-->Z
V-->8
V-->B
V-->10
V-->L
V-->E
W-->5
W-->B
W-->F
W-->Z
W-->10
W-->4
W-->I
W-->G
Y-->10
Z-->10
Z-->5
Z-->B
